spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: yolofarm_service

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/yolofarm_db}
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASS:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


  data:
    redis:
      url: ${REDIS_URL}

#  data:
#    redis:
#      host: localhost
#      port: 6379

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 300000 # in second
  refreshable-duration: 1800000 # in second

adafruit:
  mqtt:
    url: tcp://io.adafruit.com:1883
    username: ${ADAFRUIT_AIO_USERNAME}
    password: ${ADAFRUIT_AIO_KEY}
    client-id: "yolofarm-backend-server"
    topic-telemetry: "${ADAFRUIT_AIO_USERNAME}/feeds/+"
    topic-control: "${ADAFRUIT_AIO_USERNAME}/feeds/dieu-khien-thiet-bi"

# CORS Configuration - add your frontend URLs here
cors:
  allowed-origins: >
    http://localhost:5173,
    http://127.0.0.1:5173,
    http://localhost:3000,
    http://127.0.0.1:3000,
    https://yolofarmapplication.onrender.com